---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: harden-pipelined-pcf
- name: terraform-state-input

outputs:
- name: terraform-state-output

run:
  path: harden-pipelined-pcf/tasks/harden-infrastructure/aws/task.sh

params:
  access_key_id:
  secret_access_key:
  region:
  prefix:
  iaas: aws
  work_dir: .
  state_dir: terraform-state-input
  output_dir: terraform-state-output
  template_dir: harden-pipelined-pcf/harden-infrastructure/aws/terraform
