---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: harden-pipelined-pcf
- name: terraform-state-input

outputs:
- name: terraform-state-output

run:
  path: harden-pipelined-pcf/tasks/harden-infrastructure/aws/task.sh

params:
  iaas:
  region:
