---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: v0.2.7

inputs:
- name: harden-pipelined-pcf
- name: terraform-state

run:
  path: harden-pipelined-pcf/tasks/apply-vm-extensions/aws/task.sh

params:
  opsman_target:
  opsman_user:
  opsman_password:
