---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: v0.2.7

inputs:
- name: pcf-pipelines
- name: terraform-state

run:
  path: pcf-pipelines/tasks/configure-ert/task.sh

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
