---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: harden-pipelined-pcf

outputs:

run:
  path: harden-pipelined-pcf/tasks/harden-director/aws/task.sh

params:
  opsman_target:
  opsman_user:
  opsman_password:
