---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    
inputs:
  - name: pcf-pipelines-base
  - name: harden-pipelined-pcf
outputs:
  - name: pcf-pipelines

run:
  path: harden-pipelined-pcfpipelines/tasks/harden-director/aws/task.sh

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USER:
  OPSMAN_PASSWORD:
